//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VR_TEST.com.sslwireless.vrtest {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="virtualrechargeBinding", Namespace="http://103.26.139.140/virtualrecharge/?wsdl")]
    public partial class virtualrechargeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetLastRechargeTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindOperatorInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOperatorInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllOperatorInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBalanceInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatusCodeMeaningOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateRechargeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateWimaxRechargeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDescoRechargeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDpdcRechargeOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitRechargeOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyMSISDNOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOperatorLimitsOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryRechargeStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelRechargeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public virtualrechargeService() {
            this.Url = global::VR_TEST.Properties.Settings.Default.VR_TEST_com_sslwireless_vrtest_virtualrechargeService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLastRechargeTimeCompletedEventHandler GetLastRechargeTimeCompleted;
        
        /// <remarks/>
        public event FindOperatorInfoCompletedEventHandler FindOperatorInfoCompleted;
        
        /// <remarks/>
        public event GetOperatorInfoCompletedEventHandler GetOperatorInfoCompleted;
        
        /// <remarks/>
        public event GetAllOperatorInfoCompletedEventHandler GetAllOperatorInfoCompleted;
        
        /// <remarks/>
        public event GetClientInfoCompletedEventHandler GetClientInfoCompleted;
        
        /// <remarks/>
        public event GetBalanceInfoCompletedEventHandler GetBalanceInfoCompleted;
        
        /// <remarks/>
        public event GetStatusCodeMeaningCompletedEventHandler GetStatusCodeMeaningCompleted;
        
        /// <remarks/>
        public event CreateRechargeCompletedEventHandler CreateRechargeCompleted;
        
        /// <remarks/>
        public event CreateWimaxRechargeCompletedEventHandler CreateWimaxRechargeCompleted;
        
        /// <remarks/>
        public event CreateDescoRechargeCompletedEventHandler CreateDescoRechargeCompleted;
        
        /// <remarks/>
        public event CreateDpdcRechargeCompletedEventHandler CreateDpdcRechargeCompleted;
        
        /// <remarks/>
        public event InitRechargeCompletedEventHandler InitRechargeCompleted;
        
        /// <remarks/>
        public event VerifyMSISDNCompletedEventHandler VerifyMSISDNCompleted;
        
        /// <remarks/>
        public event GetOperatorLimitsCompletedEventHandler GetOperatorLimitsCompleted;
        
        /// <remarks/>
        public event QueryRechargeStatusCompletedEventHandler QueryRechargeStatusCompleted;
        
        /// <remarks/>
        public event CancelRechargeCompletedEventHandler CancelRechargeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#GetLastRechargeTime", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("last_recharge_time")]
        public string GetLastRechargeTime(string client_id, string operator_id, string msisdn) {
            object[] results = this.Invoke("GetLastRechargeTime", new object[] {
                        client_id,
                        operator_id,
                        msisdn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastRechargeTimeAsync(string client_id, string operator_id, string msisdn) {
            this.GetLastRechargeTimeAsync(client_id, operator_id, msisdn, null);
        }
        
        /// <remarks/>
        public void GetLastRechargeTimeAsync(string client_id, string operator_id, string msisdn, object userState) {
            if ((this.GetLastRechargeTimeOperationCompleted == null)) {
                this.GetLastRechargeTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastRechargeTimeOperationCompleted);
            }
            this.InvokeAsync("GetLastRechargeTime", new object[] {
                        client_id,
                        operator_id,
                        msisdn}, this.GetLastRechargeTimeOperationCompleted, userState);
        }
        
        private void OnGetLastRechargeTimeOperationCompleted(object arg) {
            if ((this.GetLastRechargeTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastRechargeTimeCompleted(this, new GetLastRechargeTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#FindOperatorInfo", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("operator_info")]
        public OperatorDataType FindOperatorInfo(string client_id, string msisdn) {
            object[] results = this.Invoke("FindOperatorInfo", new object[] {
                        client_id,
                        msisdn});
            return ((OperatorDataType)(results[0]));
        }
        
        /// <remarks/>
        public void FindOperatorInfoAsync(string client_id, string msisdn) {
            this.FindOperatorInfoAsync(client_id, msisdn, null);
        }
        
        /// <remarks/>
        public void FindOperatorInfoAsync(string client_id, string msisdn, object userState) {
            if ((this.FindOperatorInfoOperationCompleted == null)) {
                this.FindOperatorInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindOperatorInfoOperationCompleted);
            }
            this.InvokeAsync("FindOperatorInfo", new object[] {
                        client_id,
                        msisdn}, this.FindOperatorInfoOperationCompleted, userState);
        }
        
        private void OnFindOperatorInfoOperationCompleted(object arg) {
            if ((this.FindOperatorInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindOperatorInfoCompleted(this, new FindOperatorInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#GetOperatorInfo", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("operator_info")]
        public OperatorDataType GetOperatorInfo(string client_id, string operator_id) {
            object[] results = this.Invoke("GetOperatorInfo", new object[] {
                        client_id,
                        operator_id});
            return ((OperatorDataType)(results[0]));
        }
        
        /// <remarks/>
        public void GetOperatorInfoAsync(string client_id, string operator_id) {
            this.GetOperatorInfoAsync(client_id, operator_id, null);
        }
        
        /// <remarks/>
        public void GetOperatorInfoAsync(string client_id, string operator_id, object userState) {
            if ((this.GetOperatorInfoOperationCompleted == null)) {
                this.GetOperatorInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOperatorInfoOperationCompleted);
            }
            this.InvokeAsync("GetOperatorInfo", new object[] {
                        client_id,
                        operator_id}, this.GetOperatorInfoOperationCompleted, userState);
        }
        
        private void OnGetOperatorInfoOperationCompleted(object arg) {
            if ((this.GetOperatorInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOperatorInfoCompleted(this, new GetOperatorInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#GetAllOperatorInfo", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("operator_info_array")]
        public ArrayOfOperatorDataType GetAllOperatorInfo(string client_id, string active_status) {
            object[] results = this.Invoke("GetAllOperatorInfo", new object[] {
                        client_id,
                        active_status});
            return ((ArrayOfOperatorDataType)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllOperatorInfoAsync(string client_id, string active_status) {
            this.GetAllOperatorInfoAsync(client_id, active_status, null);
        }
        
        /// <remarks/>
        public void GetAllOperatorInfoAsync(string client_id, string active_status, object userState) {
            if ((this.GetAllOperatorInfoOperationCompleted == null)) {
                this.GetAllOperatorInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllOperatorInfoOperationCompleted);
            }
            this.InvokeAsync("GetAllOperatorInfo", new object[] {
                        client_id,
                        active_status}, this.GetAllOperatorInfoOperationCompleted, userState);
        }
        
        private void OnGetAllOperatorInfoOperationCompleted(object arg) {
            if ((this.GetAllOperatorInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllOperatorInfoCompleted(this, new GetAllOperatorInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#GetClientInfo", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("client_info")]
        public ClientDataType GetClientInfo(string client_id) {
            object[] results = this.Invoke("GetClientInfo", new object[] {
                        client_id});
            return ((ClientDataType)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientInfoAsync(string client_id) {
            this.GetClientInfoAsync(client_id, null);
        }
        
        /// <remarks/>
        public void GetClientInfoAsync(string client_id, object userState) {
            if ((this.GetClientInfoOperationCompleted == null)) {
                this.GetClientInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientInfoOperationCompleted);
            }
            this.InvokeAsync("GetClientInfo", new object[] {
                        client_id}, this.GetClientInfoOperationCompleted, userState);
        }
        
        private void OnGetClientInfoOperationCompleted(object arg) {
            if ((this.GetClientInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientInfoCompleted(this, new GetClientInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#GetBalanceInfo", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("stock_balance")]
        public ClientBalanceDataType GetBalanceInfo(string client_id) {
            object[] results = this.Invoke("GetBalanceInfo", new object[] {
                        client_id});
            return ((ClientBalanceDataType)(results[0]));
        }
        
        /// <remarks/>
        public void GetBalanceInfoAsync(string client_id) {
            this.GetBalanceInfoAsync(client_id, null);
        }
        
        /// <remarks/>
        public void GetBalanceInfoAsync(string client_id, object userState) {
            if ((this.GetBalanceInfoOperationCompleted == null)) {
                this.GetBalanceInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBalanceInfoOperationCompleted);
            }
            this.InvokeAsync("GetBalanceInfo", new object[] {
                        client_id}, this.GetBalanceInfoOperationCompleted, userState);
        }
        
        private void OnGetBalanceInfoOperationCompleted(object arg) {
            if ((this.GetBalanceInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBalanceInfoCompleted(this, new GetBalanceInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#GetStatusCodeMeaning", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public string GetStatusCodeMeaning(string client_id, string status_code) {
            object[] results = this.Invoke("GetStatusCodeMeaning", new object[] {
                        client_id,
                        status_code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusCodeMeaningAsync(string client_id, string status_code) {
            this.GetStatusCodeMeaningAsync(client_id, status_code, null);
        }
        
        /// <remarks/>
        public void GetStatusCodeMeaningAsync(string client_id, string status_code, object userState) {
            if ((this.GetStatusCodeMeaningOperationCompleted == null)) {
                this.GetStatusCodeMeaningOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusCodeMeaningOperationCompleted);
            }
            this.InvokeAsync("GetStatusCodeMeaning", new object[] {
                        client_id,
                        status_code}, this.GetStatusCodeMeaningOperationCompleted, userState);
        }
        
        private void OnGetStatusCodeMeaningOperationCompleted(object arg) {
            if ((this.GetStatusCodeMeaningCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusCodeMeaningCompleted(this, new GetStatusCodeMeaningCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#CreateRecharge", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("recharge_response")]
        public RechargeResponseDataType CreateRecharge(string client_id, string client_pass, string guid, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string operator_id, string recipient_msisdn, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string amount, string connection_type, string sender_id, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string priority, string success_url, string failure_url) {
            object[] results = this.Invoke("CreateRecharge", new object[] {
                        client_id,
                        client_pass,
                        guid,
                        operator_id,
                        recipient_msisdn,
                        amount,
                        connection_type,
                        sender_id,
                        priority,
                        success_url,
                        failure_url});
            return ((RechargeResponseDataType)(results[0]));
        }
        
        /// <remarks/>
        public void CreateRechargeAsync(string client_id, string client_pass, string guid, string operator_id, string recipient_msisdn, string amount, string connection_type, string sender_id, string priority, string success_url, string failure_url) {
            this.CreateRechargeAsync(client_id, client_pass, guid, operator_id, recipient_msisdn, amount, connection_type, sender_id, priority, success_url, failure_url, null);
        }
        
        /// <remarks/>
        public void CreateRechargeAsync(string client_id, string client_pass, string guid, string operator_id, string recipient_msisdn, string amount, string connection_type, string sender_id, string priority, string success_url, string failure_url, object userState) {
            if ((this.CreateRechargeOperationCompleted == null)) {
                this.CreateRechargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateRechargeOperationCompleted);
            }
            this.InvokeAsync("CreateRecharge", new object[] {
                        client_id,
                        client_pass,
                        guid,
                        operator_id,
                        recipient_msisdn,
                        amount,
                        connection_type,
                        sender_id,
                        priority,
                        success_url,
                        failure_url}, this.CreateRechargeOperationCompleted, userState);
        }
        
        private void OnCreateRechargeOperationCompleted(object arg) {
            if ((this.CreateRechargeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateRechargeCompleted(this, new CreateRechargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#CreateWimaxRecharge", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("recharge_response")]
        public RechargeResponseDataType CreateWimaxRecharge(string client_id, string client_pass, string guid, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string operator_id, string user_account, string amount, string connection_type, string sender_id, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string priority, string success_url, string failure_url) {
            object[] results = this.Invoke("CreateWimaxRecharge", new object[] {
                        client_id,
                        client_pass,
                        guid,
                        operator_id,
                        user_account,
                        amount,
                        connection_type,
                        sender_id,
                        priority,
                        success_url,
                        failure_url});
            return ((RechargeResponseDataType)(results[0]));
        }
        
        /// <remarks/>
        public void CreateWimaxRechargeAsync(string client_id, string client_pass, string guid, string operator_id, string user_account, string amount, string connection_type, string sender_id, string priority, string success_url, string failure_url) {
            this.CreateWimaxRechargeAsync(client_id, client_pass, guid, operator_id, user_account, amount, connection_type, sender_id, priority, success_url, failure_url, null);
        }
        
        /// <remarks/>
        public void CreateWimaxRechargeAsync(string client_id, string client_pass, string guid, string operator_id, string user_account, string amount, string connection_type, string sender_id, string priority, string success_url, string failure_url, object userState) {
            if ((this.CreateWimaxRechargeOperationCompleted == null)) {
                this.CreateWimaxRechargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateWimaxRechargeOperationCompleted);
            }
            this.InvokeAsync("CreateWimaxRecharge", new object[] {
                        client_id,
                        client_pass,
                        guid,
                        operator_id,
                        user_account,
                        amount,
                        connection_type,
                        sender_id,
                        priority,
                        success_url,
                        failure_url}, this.CreateWimaxRechargeOperationCompleted, userState);
        }
        
        private void OnCreateWimaxRechargeOperationCompleted(object arg) {
            if ((this.CreateWimaxRechargeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateWimaxRechargeCompleted(this, new CreateWimaxRechargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#CreateDescoRecharge", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("recharge_response")]
        public RechargeResponseDataType CreateDescoRecharge(string client_id, string client_pass, string guid, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string operator_id, string user_account, string bill_no, string amount, string connection_type, string sender_id, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string priority, string success_url, string failure_url) {
            object[] results = this.Invoke("CreateDescoRecharge", new object[] {
                        client_id,
                        client_pass,
                        guid,
                        operator_id,
                        user_account,
                        bill_no,
                        amount,
                        connection_type,
                        sender_id,
                        priority,
                        success_url,
                        failure_url});
            return ((RechargeResponseDataType)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDescoRechargeAsync(string client_id, string client_pass, string guid, string operator_id, string user_account, string bill_no, string amount, string connection_type, string sender_id, string priority, string success_url, string failure_url) {
            this.CreateDescoRechargeAsync(client_id, client_pass, guid, operator_id, user_account, bill_no, amount, connection_type, sender_id, priority, success_url, failure_url, null);
        }
        
        /// <remarks/>
        public void CreateDescoRechargeAsync(string client_id, string client_pass, string guid, string operator_id, string user_account, string bill_no, string amount, string connection_type, string sender_id, string priority, string success_url, string failure_url, object userState) {
            if ((this.CreateDescoRechargeOperationCompleted == null)) {
                this.CreateDescoRechargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDescoRechargeOperationCompleted);
            }
            this.InvokeAsync("CreateDescoRecharge", new object[] {
                        client_id,
                        client_pass,
                        guid,
                        operator_id,
                        user_account,
                        bill_no,
                        amount,
                        connection_type,
                        sender_id,
                        priority,
                        success_url,
                        failure_url}, this.CreateDescoRechargeOperationCompleted, userState);
        }
        
        private void OnCreateDescoRechargeOperationCompleted(object arg) {
            if ((this.CreateDescoRechargeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDescoRechargeCompleted(this, new CreateDescoRechargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#CreateDpdcRecharge", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("recharge_response")]
        public RechargeResponseDataType CreateDpdcRecharge(string client_id, string client_pass, string guid, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string operator_id, string user_account, string bill_month, string location_code, string amount, string connection_type, string sender_id, [System.Xml.Serialization.SoapElementAttribute(DataType="integer")] string priority, string success_url, string failure_url) {
            object[] results = this.Invoke("CreateDpdcRecharge", new object[] {
                        client_id,
                        client_pass,
                        guid,
                        operator_id,
                        user_account,
                        bill_month,
                        location_code,
                        amount,
                        connection_type,
                        sender_id,
                        priority,
                        success_url,
                        failure_url});
            return ((RechargeResponseDataType)(results[0]));
        }
        
        /// <remarks/>
        public void CreateDpdcRechargeAsync(string client_id, string client_pass, string guid, string operator_id, string user_account, string bill_month, string location_code, string amount, string connection_type, string sender_id, string priority, string success_url, string failure_url) {
            this.CreateDpdcRechargeAsync(client_id, client_pass, guid, operator_id, user_account, bill_month, location_code, amount, connection_type, sender_id, priority, success_url, failure_url, null);
        }
        
        /// <remarks/>
        public void CreateDpdcRechargeAsync(string client_id, string client_pass, string guid, string operator_id, string user_account, string bill_month, string location_code, string amount, string connection_type, string sender_id, string priority, string success_url, string failure_url, object userState) {
            if ((this.CreateDpdcRechargeOperationCompleted == null)) {
                this.CreateDpdcRechargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDpdcRechargeOperationCompleted);
            }
            this.InvokeAsync("CreateDpdcRecharge", new object[] {
                        client_id,
                        client_pass,
                        guid,
                        operator_id,
                        user_account,
                        bill_month,
                        location_code,
                        amount,
                        connection_type,
                        sender_id,
                        priority,
                        success_url,
                        failure_url}, this.CreateDpdcRechargeOperationCompleted, userState);
        }
        
        private void OnCreateDpdcRechargeOperationCompleted(object arg) {
            if ((this.CreateDpdcRechargeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDpdcRechargeCompleted(this, new CreateDpdcRechargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#InitRecharge", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("recharge_response")]
        public RechargeResponseDataType InitRecharge(string client_id, string client_pass, string guid, string vr_guid, string success_url, string failure_url) {
            object[] results = this.Invoke("InitRecharge", new object[] {
                        client_id,
                        client_pass,
                        guid,
                        vr_guid,
                        success_url,
                        failure_url});
            return ((RechargeResponseDataType)(results[0]));
        }
        
        /// <remarks/>
        public void InitRechargeAsync(string client_id, string client_pass, string guid, string vr_guid, string success_url, string failure_url) {
            this.InitRechargeAsync(client_id, client_pass, guid, vr_guid, success_url, failure_url, null);
        }
        
        /// <remarks/>
        public void InitRechargeAsync(string client_id, string client_pass, string guid, string vr_guid, string success_url, string failure_url, object userState) {
            if ((this.InitRechargeOperationCompleted == null)) {
                this.InitRechargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitRechargeOperationCompleted);
            }
            this.InvokeAsync("InitRecharge", new object[] {
                        client_id,
                        client_pass,
                        guid,
                        vr_guid,
                        success_url,
                        failure_url}, this.InitRechargeOperationCompleted, userState);
        }
        
        private void OnInitRechargeOperationCompleted(object arg) {
            if ((this.InitRechargeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitRechargeCompleted(this, new InitRechargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#VerifyMSISDN", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("result", DataType="integer")]
        public string VerifyMSISDN(string client_id, string msisdn) {
            object[] results = this.Invoke("VerifyMSISDN", new object[] {
                        client_id,
                        msisdn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyMSISDNAsync(string client_id, string msisdn) {
            this.VerifyMSISDNAsync(client_id, msisdn, null);
        }
        
        /// <remarks/>
        public void VerifyMSISDNAsync(string client_id, string msisdn, object userState) {
            if ((this.VerifyMSISDNOperationCompleted == null)) {
                this.VerifyMSISDNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyMSISDNOperationCompleted);
            }
            this.InvokeAsync("VerifyMSISDN", new object[] {
                        client_id,
                        msisdn}, this.VerifyMSISDNOperationCompleted, userState);
        }
        
        private void OnVerifyMSISDNOperationCompleted(object arg) {
            if ((this.VerifyMSISDNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyMSISDNCompleted(this, new VerifyMSISDNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#GetOperatorLimits", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("operator_limits")]
        public OperatorLimitsDataType GetOperatorLimits(string client_id, string operator_id) {
            object[] results = this.Invoke("GetOperatorLimits", new object[] {
                        client_id,
                        operator_id});
            return ((OperatorLimitsDataType)(results[0]));
        }
        
        /// <remarks/>
        public void GetOperatorLimitsAsync(string client_id, string operator_id) {
            this.GetOperatorLimitsAsync(client_id, operator_id, null);
        }
        
        /// <remarks/>
        public void GetOperatorLimitsAsync(string client_id, string operator_id, object userState) {
            if ((this.GetOperatorLimitsOperationCompleted == null)) {
                this.GetOperatorLimitsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOperatorLimitsOperationCompleted);
            }
            this.InvokeAsync("GetOperatorLimits", new object[] {
                        client_id,
                        operator_id}, this.GetOperatorLimitsOperationCompleted, userState);
        }
        
        private void OnGetOperatorLimitsOperationCompleted(object arg) {
            if ((this.GetOperatorLimitsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOperatorLimitsCompleted(this, new GetOperatorLimitsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#QueryRechargeStatus", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("recharge_request")]
        public RechargeRequestDataType QueryRechargeStatus(string client_id, string guid, string vr_guid) {
            object[] results = this.Invoke("QueryRechargeStatus", new object[] {
                        client_id,
                        guid,
                        vr_guid});
            return ((RechargeRequestDataType)(results[0]));
        }
        
        /// <remarks/>
        public void QueryRechargeStatusAsync(string client_id, string guid, string vr_guid) {
            this.QueryRechargeStatusAsync(client_id, guid, vr_guid, null);
        }
        
        /// <remarks/>
        public void QueryRechargeStatusAsync(string client_id, string guid, string vr_guid, object userState) {
            if ((this.QueryRechargeStatusOperationCompleted == null)) {
                this.QueryRechargeStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryRechargeStatusOperationCompleted);
            }
            this.InvokeAsync("QueryRechargeStatus", new object[] {
                        client_id,
                        guid,
                        vr_guid}, this.QueryRechargeStatusOperationCompleted, userState);
        }
        
        private void OnQueryRechargeStatusOperationCompleted(object arg) {
            if ((this.QueryRechargeStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryRechargeStatusCompleted(this, new QueryRechargeStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:soap-iso#CancelRecharge", RequestNamespace="urn:soap-iso", ResponseNamespace="urn:soap-iso")]
        [return: System.Xml.Serialization.SoapElementAttribute("recharge_response")]
        public RechargeResponseDataType CancelRecharge(string client_id, string client_pass, string guid, string vr_guid, string cancel_reason) {
            object[] results = this.Invoke("CancelRecharge", new object[] {
                        client_id,
                        client_pass,
                        guid,
                        vr_guid,
                        cancel_reason});
            return ((RechargeResponseDataType)(results[0]));
        }
        
        /// <remarks/>
        public void CancelRechargeAsync(string client_id, string client_pass, string guid, string vr_guid, string cancel_reason) {
            this.CancelRechargeAsync(client_id, client_pass, guid, vr_guid, cancel_reason, null);
        }
        
        /// <remarks/>
        public void CancelRechargeAsync(string client_id, string client_pass, string guid, string vr_guid, string cancel_reason, object userState) {
            if ((this.CancelRechargeOperationCompleted == null)) {
                this.CancelRechargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelRechargeOperationCompleted);
            }
            this.InvokeAsync("CancelRecharge", new object[] {
                        client_id,
                        client_pass,
                        guid,
                        vr_guid,
                        cancel_reason}, this.CancelRechargeOperationCompleted, userState);
        }
        
        private void OnCancelRechargeOperationCompleted(object arg) {
            if ((this.CancelRechargeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelRechargeCompleted(this, new CancelRechargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://103.26.139.140/virtualrecharge/?wsdl")]
    public partial class OperatorDataType {
        
        private int operator_idField;
        
        private string operator_nameField;
        
        private string msisdn_prefixField;
        
        private int active_statusField;
        
        /// <remarks/>
        public int operator_id {
            get {
                return this.operator_idField;
            }
            set {
                this.operator_idField = value;
            }
        }
        
        /// <remarks/>
        public string operator_name {
            get {
                return this.operator_nameField;
            }
            set {
                this.operator_nameField = value;
            }
        }
        
        /// <remarks/>
        public string msisdn_prefix {
            get {
                return this.msisdn_prefixField;
            }
            set {
                this.msisdn_prefixField = value;
            }
        }
        
        /// <remarks/>
        public int active_status {
            get {
                return this.active_statusField;
            }
            set {
                this.active_statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://103.26.139.140/virtualrecharge/?wsdl")]
    public partial class RechargeRequestDataType {
        
        private string guidField;
        
        private string vr_guidField;
        
        private string request_timeField;
        
        private string operator_idField;
        
        private string recipient_msisdnField;
        
        private string connection_typeField;
        
        private string amountField;
        
        private string init_timeField;
        
        private string cancel_timeField;
        
        private string recharge_dateField;
        
        private string recharge_statusField;
        
        private string messageField;
        
        /// <remarks/>
        public string guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        public string vr_guid {
            get {
                return this.vr_guidField;
            }
            set {
                this.vr_guidField = value;
            }
        }
        
        /// <remarks/>
        public string request_time {
            get {
                return this.request_timeField;
            }
            set {
                this.request_timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string operator_id {
            get {
                return this.operator_idField;
            }
            set {
                this.operator_idField = value;
            }
        }
        
        /// <remarks/>
        public string recipient_msisdn {
            get {
                return this.recipient_msisdnField;
            }
            set {
                this.recipient_msisdnField = value;
            }
        }
        
        /// <remarks/>
        public string connection_type {
            get {
                return this.connection_typeField;
            }
            set {
                this.connection_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string init_time {
            get {
                return this.init_timeField;
            }
            set {
                this.init_timeField = value;
            }
        }
        
        /// <remarks/>
        public string cancel_time {
            get {
                return this.cancel_timeField;
            }
            set {
                this.cancel_timeField = value;
            }
        }
        
        /// <remarks/>
        public string recharge_date {
            get {
                return this.recharge_dateField;
            }
            set {
                this.recharge_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string recharge_status {
            get {
                return this.recharge_statusField;
            }
            set {
                this.recharge_statusField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://103.26.139.140/virtualrecharge/?wsdl")]
    public partial class OperatorLimitsDataType {
        
        private string operator_idField;
        
        private string prepaid_low_limitField;
        
        private string prepaid_high_limitField;
        
        private string postpaid_low_limitField;
        
        private string postpaid_high_limitField;
        
        private string prepaid_time_limitField;
        
        private string postpaid_time_limitField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string operator_id {
            get {
                return this.operator_idField;
            }
            set {
                this.operator_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string prepaid_low_limit {
            get {
                return this.prepaid_low_limitField;
            }
            set {
                this.prepaid_low_limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string prepaid_high_limit {
            get {
                return this.prepaid_high_limitField;
            }
            set {
                this.prepaid_high_limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string postpaid_low_limit {
            get {
                return this.postpaid_low_limitField;
            }
            set {
                this.postpaid_low_limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string postpaid_high_limit {
            get {
                return this.postpaid_high_limitField;
            }
            set {
                this.postpaid_high_limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string prepaid_time_limit {
            get {
                return this.prepaid_time_limitField;
            }
            set {
                this.prepaid_time_limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string postpaid_time_limit {
            get {
                return this.postpaid_time_limitField;
            }
            set {
                this.postpaid_time_limitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://103.26.139.140/virtualrecharge/?wsdl")]
    public partial class RechargeResponseDataType {
        
        private string vr_guidField;
        
        private string recharge_statusField;
        
        private string messageField;
        
        /// <remarks/>
        public string vr_guid {
            get {
                return this.vr_guidField;
            }
            set {
                this.vr_guidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string recharge_status {
            get {
                return this.recharge_statusField;
            }
            set {
                this.recharge_statusField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://103.26.139.140/virtualrecharge/?wsdl")]
    public partial class ClientBalanceDataType {
        
        private string client_user_idField;
        
        private string available_creditField;
        
        private string last_updated_timeField;
        
        /// <remarks/>
        public string client_user_id {
            get {
                return this.client_user_idField;
            }
            set {
                this.client_user_idField = value;
            }
        }
        
        /// <remarks/>
        public string available_credit {
            get {
                return this.available_creditField;
            }
            set {
                this.available_creditField = value;
            }
        }
        
        /// <remarks/>
        public string last_updated_time {
            get {
                return this.last_updated_timeField;
            }
            set {
                this.last_updated_timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://103.26.139.140/virtualrecharge/?wsdl")]
    public partial class ClientDataType {
        
        private string client_user_idField;
        
        private string client_nameField;
        
        private string client_contact_detailsField;
        
        private int client_active_statusField;
        
        /// <remarks/>
        public string client_user_id {
            get {
                return this.client_user_idField;
            }
            set {
                this.client_user_idField = value;
            }
        }
        
        /// <remarks/>
        public string client_name {
            get {
                return this.client_nameField;
            }
            set {
                this.client_nameField = value;
            }
        }
        
        /// <remarks/>
        public string client_contact_details {
            get {
                return this.client_contact_detailsField;
            }
            set {
                this.client_contact_detailsField = value;
            }
        }
        
        /// <remarks/>
        public int client_active_status {
            get {
                return this.client_active_statusField;
            }
            set {
                this.client_active_statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://103.26.139.140/virtualrecharge/?wsdl")]
    public partial class ArrayOfOperatorDataType {
        
        private OperatorDataType[] operator_info_arrayField;
        
        /// <remarks/>
        public OperatorDataType[] operator_info_array {
            get {
                return this.operator_info_arrayField;
            }
            set {
                this.operator_info_arrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetLastRechargeTimeCompletedEventHandler(object sender, GetLastRechargeTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastRechargeTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastRechargeTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FindOperatorInfoCompletedEventHandler(object sender, FindOperatorInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindOperatorInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindOperatorInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperatorDataType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperatorDataType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetOperatorInfoCompletedEventHandler(object sender, GetOperatorInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOperatorInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOperatorInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperatorDataType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperatorDataType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAllOperatorInfoCompletedEventHandler(object sender, GetAllOperatorInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllOperatorInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllOperatorInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ArrayOfOperatorDataType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArrayOfOperatorDataType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetClientInfoCompletedEventHandler(object sender, GetClientInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientDataType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientDataType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetBalanceInfoCompletedEventHandler(object sender, GetBalanceInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBalanceInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBalanceInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientBalanceDataType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientBalanceDataType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetStatusCodeMeaningCompletedEventHandler(object sender, GetStatusCodeMeaningCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusCodeMeaningCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusCodeMeaningCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateRechargeCompletedEventHandler(object sender, CreateRechargeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateRechargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateRechargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RechargeResponseDataType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RechargeResponseDataType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateWimaxRechargeCompletedEventHandler(object sender, CreateWimaxRechargeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateWimaxRechargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateWimaxRechargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RechargeResponseDataType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RechargeResponseDataType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateDescoRechargeCompletedEventHandler(object sender, CreateDescoRechargeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDescoRechargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDescoRechargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RechargeResponseDataType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RechargeResponseDataType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateDpdcRechargeCompletedEventHandler(object sender, CreateDpdcRechargeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateDpdcRechargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateDpdcRechargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RechargeResponseDataType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RechargeResponseDataType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void InitRechargeCompletedEventHandler(object sender, InitRechargeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitRechargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitRechargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RechargeResponseDataType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RechargeResponseDataType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void VerifyMSISDNCompletedEventHandler(object sender, VerifyMSISDNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyMSISDNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyMSISDNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetOperatorLimitsCompletedEventHandler(object sender, GetOperatorLimitsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOperatorLimitsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOperatorLimitsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperatorLimitsDataType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperatorLimitsDataType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryRechargeStatusCompletedEventHandler(object sender, QueryRechargeStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryRechargeStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryRechargeStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RechargeRequestDataType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RechargeRequestDataType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CancelRechargeCompletedEventHandler(object sender, CancelRechargeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelRechargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelRechargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RechargeResponseDataType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RechargeResponseDataType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591